version = 0.1
default-task = 'build'

[[task]]
name = 'npm:install'
targets = [
    'node_modules',
    'package-lock.json',
]
deps = ['package.json']
validation = 'ok-only'
display = 'init-only'
run = 'npm install'

[[task]]
name = 'build'
targets = ['sandbox.html']
deps = [
    'sandbox.html',
    'src/**/*',
    'npm:install',
]
invalidation = 'always'
run = '''
    jspm clear-cache
    jspm inject $DEP -o $TARGET --preload --integrity
'''

[[task]]
name = 'deploy'
run = 'ipfs --api=/ip4/127.0.0.1/tcp/45005 name publish /ipfs/$(ipfs --api=/ip4/127.0.0.1/tcp/45005 add -r . -Q --cid-version=1)'
